version: '3.2'
services:
  web:
    container_name: app
    build:
      context: ./dockerfile
      dockerfile: app
    ports:
      - "80:80"
      - "443:443"
      - "1323:1323"
    volumes:
      - ./ubuntu:/home/
    tty: true
  db:
    container_name: db
    build:
      context: ./dockerfile
      dockerfile: db
    ports:
      - "3306:3306"
    volumes:
      - ./database:/home/
    environment:
      MYSQL_ROOT_PASSWORD: password